### ISSUE TITLE
关于LCnet、Dnet与lio系统整合运行的问题

### ISSUE THREAD

**Issue by Tianci-Wen** [KangchengLiu/DLC_LiDAR_SLAM#1]
您好，感谢您优秀的工作，但我在readme中没找到如何将DNet与LCNet与fastlio2、liosam结合起来运行
您的LIO-SAM_DLC、LIO-SAM_Integrated_DLC、LVI-SAM_DLC里面均没有LCnet，请问您能详细说明下使用流程吗，万分感谢！

**Comment by KangchengLiu** [comment]
We use LC-Net for the offline loop closure and integrate it into bundle adjustment to improve the precision in global optimization.   The detailed procedure is now deployed into projects and will be updated when available.
